CREATE TABLE users(
   UID INT NOT NULL AUTO_INCREMENT,
   FIRST_NAME VARCHAR(255) NOT NULL,
   SURNAME VARCHAR(255) NOT NULL,
   EMAIL VARCHAR(255) NOT NULL UNIQUE,
   PASSWORD VARCHAR(255) NOT NULL,
   PHONE VARCHAR (25) NOT NULL,
   ADDRESS VARCHAR(255) NOT NULL, 
   ORGANIZATION VARCHAR(255) NOT NULL, 
   PACKAGE VARCHAR(255) NOT NULL, 
   CC_NUMBER VARCHAR(255) NOT NULL UNIQUE,
   CC_PIN VARCHAR(4) NOT NULL,  
   PRIMARY KEY (UID)
);

CREATE TABLE subscriptions (
   EMAIL VARCHAR(255) NOT NULL,
   CURRENT_SUB INT DEFAULT 0,
   PACKAGE VARCHAR(255) NOT NULL,
   D_SUBSCRIBED DATETIME DEFAULT CURRENT_TIMESTAMP,
   D_UNSUBSCRIBED DATETIME DEFAULT NULL
);
